// Calcite Components — solo quelli usati in JSX.
import '@esri/calcite-components/components/calcite-action'
import '@esri/calcite-components/components/calcite-action-bar'
import '@esri/calcite-components/components/calcite-action-group'
import '@esri/calcite-components/components/calcite-button'
import '@esri/calcite-components/components/calcite-checkbox'
import '@esri/calcite-components/components/calcite-chip'
import '@esri/calcite-components/components/calcite-dialog'
import '@esri/calcite-components/components/calcite-icon'
import '@esri/calcite-components/components/calcite-input-date-picker'
import '@esri/calcite-components/components/calcite-input-number'
import '@esri/calcite-components/components/calcite-input-text'
import '@esri/calcite-components/components/calcite-input-time-picker'
import '@esri/calcite-components/components/calcite-label'
import '@esri/calcite-components/components/calcite-list'
import '@esri/calcite-components/components/calcite-list-item'
import '@esri/calcite-components/components/calcite-loader'
import '@esri/calcite-components/components/calcite-notice'
import '@esri/calcite-components/components/calcite-panel'
import '@esri/calcite-components/components/calcite-segmented-control'
import '@esri/calcite-components/components/calcite-segmented-control-item'
import '@esri/calcite-components/components/calcite-shell'
import '@esri/calcite-components/components/calcite-shell-panel'
import '@esri/calcite-components/components/calcite-switch'

import '@arcgis/map-components/components/arcgis-sketch'
